// <auto-generated />
using System;
using EventTracking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventTracking.Persistence.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260919041219_BrokerOutboxAttemptsDefault")]
    partial class BrokerOutboxAttemptsDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventTracking.Persistence.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "OccurredAt", "Id");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.BrokerOutboxRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("ProjectId", "EventId");

                    b.HasIndex("CompletedAt", "DeadLetteredAt", "NextAttemptAt", "CreatedAt");

                    b.ToTable("broker_outbox", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.ClickHouseProjectionRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ProjectId", "EventId");

                    b.HasIndex("CompletedAt", "CreatedAt");

                    b.ToTable("clickhouse_projection", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.CredentialRecord", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.HasKey("KeyHash");

                    b.HasIndex("ProjectId");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.DashboardUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("SessionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("session_version");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("dashboard_users", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.EventIdentity", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("StoredBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("stored_bytes");

                    b.HasKey("ProjectId", "EventId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("event_identity", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.EventRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("anonymous_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId", "EventId");

                    b.HasIndex("Properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Properties"), "gin");

                    b.HasIndex("ProjectId", "EventType", "OccurredAt");

                    b.HasIndex("ProjectId", "OccurredAt", "EventId");

                    b.HasIndex("ProjectId", "UserId", "OccurredAt", "EventId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.EventSchemaRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.HasKey("ProjectId", "EventType", "Version");

                    b.ToTable("event_schemas", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.InboxRecord", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("ProjectId", "EventId");

                    b.HasIndex("ReceivedAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.LoginRateLimit", b =>
                {
                    b.Property<string>("Bucket")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bucket");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Bucket");

                    b.ToTable("login_rate_limits", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.ProjectMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<bool>("CanDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("can_demo");

                    b.Property<bool>("CanManage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_manage");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_memberships", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.ProjectRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<long>("EventCount")
                        .HasColumnType("bigint")
                        .HasColumnName("event_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<long>("StoredBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("stored_bytes");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.SavedQueryView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId", "Name")
                        .IsUnique();

                    b.ToTable("saved_query_views", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.StorageState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile");

                    b.HasKey("Id");

                    b.ToTable("storage_state", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("EventTracking.Persistence.BrokerOutboxRecord", b =>
                {
                    b.HasOne("EventTracking.Persistence.EventIdentity", null)
                        .WithOne()
                        .HasForeignKey("EventTracking.Persistence.BrokerOutboxRecord", "ProjectId", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.ClickHouseProjectionRecord", b =>
                {
                    b.HasOne("EventTracking.Persistence.EventIdentity", null)
                        .WithOne()
                        .HasForeignKey("EventTracking.Persistence.ClickHouseProjectionRecord", "ProjectId", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.CredentialRecord", b =>
                {
                    b.HasOne("EventTracking.Persistence.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.EventIdentity", b =>
                {
                    b.HasOne("EventTracking.Persistence.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.EventRecord", b =>
                {
                    b.HasOne("EventTracking.Persistence.EventIdentity", null)
                        .WithOne()
                        .HasForeignKey("EventTracking.Persistence.EventRecord", "ProjectId", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.EventSchemaRecord", b =>
                {
                    b.HasOne("EventTracking.Persistence.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.InboxRecord", b =>
                {
                    b.HasOne("EventTracking.Persistence.EventIdentity", null)
                        .WithOne()
                        .HasForeignKey("EventTracking.Persistence.InboxRecord", "ProjectId", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.ProjectMembership", b =>
                {
                    b.HasOne("EventTracking.Persistence.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTracking.Persistence.DashboardUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventTracking.Persistence.SavedQueryView", b =>
                {
                    b.HasOne("EventTracking.Persistence.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTracking.Persistence.DashboardUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
